env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
    - make test
builds:
    - main: ./cmd/tubectl
      binary: tubectl

      gcflags:
        - all=-trimpath={{.Env.GOPATH}}

      ldflags:
       - -s -w -X main.version={{.Env.VERSION}}
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

nfpm:
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  replacements:
    amd64: 64-bit
    386: 32-bit
    darwin: macOS
    linux: Tux
  vendor: we@reconquest.io

  homepage: https://github.com/reconquest/quadro

  maintainer: we@reconquest.io

  description: Toolkit for effective working with kubernetes clusters

  license: MIT

  formats:
    - deb
    - rpm

  bindir: /usr/bin
